# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83b612a9bd4428393599b2cac2cbd09018be7b87567532324564bae4ece9105dc81e01f7e1eb7481d1d465612f359ee6172722266b69d1f544b0443dcd4a09c1

test:
  secret_key_base: 33f4266366169bac9f81a0e3f8df185319fc1ad21513e1a482e0db739d1a68254eb29c6a7e3b20c331908ffe9cce362d977ae11879a2afc8b55e99d786d2cb4b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
